import type { Article, Order, Product } from "./types";

/**
 * FALLBACK / SEED DATA — dipakai saat Supabase belum dikonfigurasi (Demo Mode)
 * dan sebagai sumber seed untuk supabase/schema.sql
 */

export const CATEGORY_TABS = [
  "Semua Kue",
  "Kue Basah Manis",
  "Gurih & Asin",
  "Paket Snack Box",
  "Kue Tampah Sultan",
  "Minuman Tradisional",
] as const;

export const FALLBACK_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "klepon-gula-aren-meluber",
    name: "Klepon Gula Aren Meluber",
    category: "Kue Basah Manis",
    price: 18000,
    unit: "Porsi isi 6 pcs",
    badges: ["Fresh Pagi Ini", "BEST SELLER"],
    description:
      "Klepon pandan dengan lumeran gula aren asli Temanggung yang meluber saat digigit. Dibuat subuh, dikukus alami dengan bahan pilihan tanpa pengawet.",
    image_url: "/images/kue/klepon.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 200,
    stock_sold: 188,
    sort_order: 1,
  },
  {
    id: "p2",
    slug: "lemper-ayam-bakar-spesial",
    name: "Lemper Ayam Bakar Spesial",
    category: "Gurih & Asin",
    price: 5500,
    unit: "Per pcs",
    badges: ["Fresh Pagi Ini", "FAVORIT HAJATAN"],
    description:
      "Lemper pulen berisi suwiran ayam bakar dibungkus daun pisang pilihan. Aroma bakar daun pisang memberikan keharuman khas yang tak tergantikan.",
    image_url: "/images/kue/lemper.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 250,
    stock_sold: 242,
    sort_order: 2,
  },
  {
    id: "p3",
    slug: "kue-lumpur-surga-pandan",
    name: "Kue Lumpur Surga Pandan",
    category: "Kue Basah Manis",
    price: 22000,
    unit: "Per box (4 cup)",
    badges: ["Fresh Pagi Ini"],
    description:
      "Kue lumpur klasik tekstur lembut meleleh dengan aroma pandan wangi sejati dan taburan kismis. Sajian nostalgia arisan keluarga.",
    image_url: "/images/kue/kue-lumpur.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 60,
    stock_sold: 41,
    sort_order: 3,
  },
  {
    id: "p4",
    slug: "lapis-legit-prunes-tradisional",
    name: "Lapis Legit Prunes Tradisional",
    category: "Kue Basah Manis",
    price: 45000,
    unit: "Per potong tebal",
    badges: ["PREMIUM BUTTER", "PRE-ORDER H-1"],
    description:
      "Lapis legit 30+ lapis premium butter, dipanggang per lapis selama 3 jam. Versi tradisional dengan topping prunes import.",
    image_url: "/images/kue/lapis-legit.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 50,
    stock_sold: 25,
    sort_order: 4,
  },
  {
    id: "p5",
    slug: "onde-onde-crispy-wijen",
    name: "Onde-onde Crispy Wijen",
    category: "Kue Basah Manis",
    price: 4000,
    unit: "Per pcs",
    badges: ["Fresh Pagi Ini"],
    description:
      "Onde-onde wijen renyah dengan isian kacang hijau halus dan gula aren. Renyah di luar, lembut manis di dalam.",
    image_url: "/images/kue/onde-onde.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 300,
    stock_sold: 220,
    sort_order: 5,
  },
  {
    id: "p6",
    slug: "bika-ambon-sarang-semut",
    name: "Bika Ambon Sarang Semut",
    category: "Kue Basah Manis",
    price: 35000,
    unit: "Kotak mini (6 potong)",
    badges: ["Resep Kuno Medan"],
    description:
      "Bika ambon sarang semut dengan tekstur berongga sempurna. Fermentasi alami 12 jam, aroma pandan dan kelapa sangrai.",
    image_url: "/images/kue/bika-ambon.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 50,
    stock_sold: 25,
    sort_order: 6,
  },
  {
    id: "p7",
    slug: "kue-mangkok-mekar-gula-aren",
    name: "Kue Mangkok Mekar Gula Aren",
    category: "Kue Basah Manis",
    price: 4500,
    unit: "Per pcs",
    badges: ["Fresh Pagi Ini"],
    description:
      "Kue mangkok mekar cantik dari tepung beras dan gula aren. Bunga mekar sempurna, legit manis alami.",
    image_url: "/images/kue/kue-mangkok.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 200,
    stock_sold: 150,
    sort_order: 7,
  },
  {
    id: "p8",
    slug: "pastel-goreng-ragout-spesial",
    name: "Pastel Goreng Ragout Spesial",
    category: "Gurih & Asin",
    price: 6000,
    unit: "Per pcs + sambal kacang",
    badges: ["Fresh Pagi Ini", "FAVORIT SNACK BOX"],
    description:
      "Pastel goreng isi ragout ayam dan wortel creamy, disajikan dengan sambal kacang rumahan. Kulit renyah tahan lama.",
    image_url: "/images/kue/pastel.svg",
    is_bundle: false,
    is_active: true,
    stock_capacity: 300,
    stock_sold: 210,
    sort_order: 8,
  },
  {
    id: "p9",
    slug: "tampah-tamu-agung-80",
    name: "Tampah Tamu Agung (Isi 80 Pcs)",
    category: "Kue Tampah Sultan",
    price: 385000,
    unit: "8 macam kue × 10 pcs",
    badges: ["PALING DIMINATI RESEPSI"],
    description:
      "Tampah bambu 60cm berisi 8 macam kue pilihan: Klepon Gula Aren, Lemper Bakar, Bika Ambon, Pastel Ragout, Kue Mangkok, Kue Lumpur, Onde Crispy, Lapis Spekuk. Gratis pita & kartu kaligrafi.",
    image_url: "/images/kue/tampah-agung.svg",
    is_bundle: true,
    is_active: true,
    stock_capacity: 15,
    stock_sold: 3,
    sort_order: 9,
  },
  {
    id: "p10",
    slug: "tampah-sedang-keluarga-40",
    name: "Tampah Sedang Keluarga (Isi 40 Pcs)",
    category: "Kue Tampah Sultan",
    price: 215000,
    unit: "Kue campur 40 pcs",
    badges: ["COCOK ARISAN"],
    description:
      "Tampah kue campur untuk arisan dan rapat 10–15 orang. Kombinasi kue basah manis dan gurih pilihan dapur.",
    image_url: "/images/kue/tampah-sedang.svg",
    is_bundle: true,
    is_active: true,
    stock_capacity: 20,
    stock_sold: 5,
    sort_order: 10,
  },
  {
    id: "p11",
    slug: "snack-box-besek-satuan",
    name: "Snack Box Besek Satuan",
    category: "Paket Snack Box",
    price: 16500,
    unit: "Per box • Min. 20 box",
    badges: ["MIN. PEMESANAN 20 BOX"],
    description:
      "Besek eksklusif isi 3 kue pilihan + 1 air mineral + sendok kayu. Cocok untuk seminar, rapat kantor, dan hantaran.",
    image_url: "/images/kue/snack-box.svg",
    is_bundle: true,
    is_active: true,
    stock_capacity: 500,
    stock_sold: 120,
    sort_order: 11,
  },
];

export const FALLBACK_ARTICLES: Article[] = [
  {
    id: "a1",
    slug: "filosofi-manis-klepon",
    title: "Filosofi Manis di Balik Kue Klepon: Lambang Kerendahan Hati dan Kejutan Rasa Nusantara",
    category: "Filosofi Tradisi",
    excerpt:
      "Di balik bentuknya yang sederhana, klepon menyimpan makna kerendahan hati — manisnya tersembunyi di dalam, tersembunyi dari pandangan.",
    content:
      "Klepon adalah kue yang mengajarkan kita tentang kerendahan hati. Dari luar ia tampak sederhana: bola-bola hijau pandan berbalur kelapa parut. Namun saat digigit, gula aren cair meluber memberikan kejutan rasa yang tak terduga.\n\nBagi masyarakat Jawa, klepon kerap menjadi bagian sajian tumpeng dan hajatan. Warna hijaunya melambangkan kesuburan dan hidup, sementara isian gula aren yang 'meluber' mengingatkan kita bahwa kebahagiaan sesungguhnya justru datang dari hal-hal yang tidak kita pamerkan.\n\nDi Toko Kue Bu Rohayah, setiap klepon dibuat dengan gula aren asli Temanggung yang dicairkan secara tradisional — bukan sirup pabrik — agar filosofi manis yang tulus ini tetap terjaga.",
    author: "Chef Dapur Tradisi",
    read_time: 5,
    views: 5200,
    is_featured: true,
    published_at: "2025-10-14",
    image_url: "/images/artikel/klepon-filosofi.svg",
  },
  {
    id: "a2",
    slug: "tips-snack-box-rapat-kantor",
    title: "5 Tips Memilih & Menyusun Snack Box Rapat Kantor agar Elegan dan Mengenyangkan",
    category: "Panduan Acara",
    excerpt:
      "Susunan snack box yang tepat membuat rapat 2 jam terasa ringkas. Begini cara menyusun komposisi gurih-manis yang proporsional.",
    content:
      "Menyusun snack box untuk rapat kantor bukan sekadar mengisi kotak. Ada ilmu komposisi di dalamnya.\n\n1. Patuhi rasio 60:40 antara gurih dan manis. Peserta rapat cenderung lebih banyak memilih gurih di awal.\n2. Sertakan satu item 'signature' yang berkesan — misalnya lemper ayam bakar dengan aroma daun pisangnya.\n3. Air mineral adalah wajib. Kotak besek kami selalu menyertakannya.\n4. Perhatikan durasi rapat: rapat 2 jam cukup 3 item, seminar sehari penuh butuh 5–6 item.\n5. Gunakan kemasan yang rapi dan seragam — kesan pertama peserta selalu dari tampilan.",
    author: "Tim Katering Pawon",
    read_time: 4,
    views: 3100,
    is_featured: false,
    published_at: "2025-10-12",
    image_url: "/images/artikel/snack-box.svg",
  },
  {
    id: "a3",
    slug: "rahasia-daun-pisang-dibakar-lemper",
    title: "Mengapa Lemper Dibungkus Daun Pisang yang Dibakar? Rahasia Aroma yang Tak Tergantikan",
    category: "Eksplorasi Kuliner",
    excerpt:
      "Ada alasan kuno di balik daun pisang yang dilewatkan di atas api sebelum membungkus lemper — dan ilmu pengetahuan modern akhirnya setuju.",
    content:
      "Sebelum membungkus lemper, para perajin terampil selalu melewatkan daun pisang di atas api sebentar. Bukan tanpa alasan.\n\nPemanasan singkat ini melembutkan serat daun sehingga lebih mudah dilipat, sekaligus membangkitkan senyawa aromatik yang membuat aroma lemper harum khas. Selain itu, panas mengurangi kelembapan permukaan daun sehingga nasi lemper tidak cepat lembek.\n\nDi dapur kami, teknik ini masih dipertahankan di setiap batch produksi subuh — karena tidak ada pengganti buatan untuk keharuman daun pisang yang dibakar.",
    author: "Bude Harum Dapur",
    read_time: 6,
    views: 2800,
    is_featured: false,
    published_at: "2025-10-10",
    image_url: "/images/artikel/daun-pisang.svg",
  },
  {
    id: "a4",
    slug: "cara-menyimpan-kue-basah-santan",
    title: "Cara Menyimpan Kue Basah Santan Agar Tetap Segar dan Tidak Cepat Basi Seharian",
    category: "Tips Dapur",
    excerpt:
      "Kue basah berbahan santan paling rawan basi. Simpan dengan cara ini agar tetap aman dikonsumsi sampai sore.",
    content:
      "Kue berbahan dasar santan seperti klepon, kue lumpur, dan nagasari memang paling rawan tercemar bakteri. Berikut panduan penyimpanan dari dapur kami:\n\n1. Simpan di suhu ruang maksimal 6–8 jam, di tempat sejuk dan tidak terkena sinar matahari langsung.\n2. Untuk penyimpanan lebih lama, masukkan ke kulkas (bukan freezer) dan hangatkan kembali dengan cara dikukus 5 menit.\n3. Jangan simpan kue basah dalam kondisi tertutup rapat saat masih hangat — uap panas akan mengembunkan dan mempercepat basi.\n4. Pisahkan kue yang sudah tersentuh dari kue yang belum — tangan mengandung bakteri yang mempercepat fermentasi.\n\nSemua kue santan dari dapur kami selalu dikirim dalam kondisi dingin setelah proses kukus, sehingga umur simpannya lebih panjang dari kue pasar umumnya.",
    author: "Peneliti Rasa Pawon",
    read_time: 5,
    views: 2400,
    is_featured: false,
    published_at: "2025-10-08",
    image_url: "/images/artikel/kue-basah.svg",
  },
  {
    id: "a5",
    slug: "beda-lapis-legit-dan-lapis-surabaya",
    title: "Beda Lapis Legit dan Lapis Surabaya: Karakter Rempah Spekuk vs Tekstur Sponge Lembut",
    category: "Kamus Kue",
    excerpt:
      "Sering tertukar karena namanya mirip, keduanya jelas berbeda dari bahan, proses, hingga karakter rasa.",
    content:
      "Lapis legit dan lapis Surabaya sering tertukar oleh pembeli kue. Padahal keduanya adalah dua kue berbeda dengan karakter yang sangat berlainan.\n\nLapis legit ( spekuk) dipanggang lapis demi lapis dengan dominasi mentega premium dan rempah spekuk — kayu manis, cengkeh, dan pala. Butuh waktu 3 jam untuk 30 lapisan. Teksturnya padat, aromanya kuat rempah.\n\nLapis Surabaya sebaliknya adalah sponge cake tiga warna yang lembut, berbahan telur dan margarin, dengan rasa manis sederhana tanpa rempah. Ia justru lebih dekat ke keluarga bolu.\n\nJadi untuk hantaran resmi yang mewah, pilih lapis legit. Untuk teman minum teh keluarga, lapis Surabaya lebih pas.",
    author: "Chef Dapur Tradisi",
    read_time: 7,
    views: 1900,
    is_featured: false,
    published_at: "2025-10-05",
    image_url: "/images/artikel/lapis.svg",
  },
  {
    id: "a6",
    slug: "kue-tampah-hantaran-lamaran-adat",
    title: "Menyiapkan Kue Tampah Cantik untuk Hantaran Lamaran Adat Tradisional",
    category: "Inspirasi Hajatan",
    excerpt:
      "Jumlah ganjil, susunan bertingkat, dan kue wajib — berikut panduan lengkap menyusun tampah lamaran sesuai adat.",
    content:
      "Hantaran lamaran adat memiliki aturan jumlah ganjil: 5, 7, atau 9 tampah. Setiap tampah menyimpan makna doa dan harapan baik untuk kedua mempelai.\n\nSusunan yang baik menggunakan prinsip bertingkat: kue kering tahan lama di bawah, kue basah premium di atas agar terlihat saat prosesi. Pita dan kartu kaligrafi menambah kesan sakral.\n\nKue wajib dalam tradisi Betawi dan Jawa antara lain: kue sepit, lapis legit, kue mangkok (lambang mekar/kebaikan), dan dodol (lambang kelekatan hubungan). Dapur kami menyediakan paket Tampah Tamu Agung lengkap dengan pita dan kartu kaligrafi sesuai permintaan adat.",
    author: "Tim Katering Pawon",
    read_time: 6,
    views: 1700,
    is_featured: false,
    published_at: "2025-10-02",
    image_url: "/images/artikel/tampah-lamaran.svg",
  },
  {
    id: "a7",
    slug: "manfaat-daun-suji-pandan-wangi",
    title: "Manfaat Daun Suji dan Pandan Wangi Asli Dibanding Pewarna Makanan Buatan",
    category: "Kesehatan & Alami",
    excerpt:
      "Warna hijau alami dari daun suji dan pandan bukan hanya soal estetika — ada kandungan yang baik untuk tubuh.",
    content:
      "Banyak kue modern menggunakan pewarna hijau sintetis. Padahal nenek moyang kita sudah memiliki dua 'penyihir hijau' alami: daun suji dan pandan wangi.\n\nDaun suji menghasilkan hijau tua yang pekat, sementara pandan memberi hijau muda dengan aroma wangi khas. Keduanya dapat dipadukan untuk gradasi warna alami tanpa bahan kimia.\n\nSelain aman, ekstrak daun suji mengandung antioksidan dan dipercaya memiliki sifat menenangkan. Di dapur kami, semua kue berwarna hijau — klepon, kue lumpur pandan, dadar gulung — 100% memakai ekstrak daun asli, sesuai prinsip 'bahan alami tanpa pengawet sintetis'.",
    author: "Bude Harum Dapur",
    read_time: 4,
    views: 1500,
    is_featured: false,
    published_at: "2025-09-28",
    image_url: "/images/artikel/daun-suji.svg",
  },
  {
    id: "a8",
    slug: "resep-onde-onde-renyah-anti-kempes",
    title: "Resep Onde-Onde Wijen Renyah Anti Kempes Walau Sudah Dingin",
    category: "Resep Warisan",
    excerpt: "Kunci onde-onde renyah ada di suhu minyak dan waktu istirahat adonan. Berikut resep turun-temurun dapur Bu Rohayah.",
    content:
      "Banyak yang gagal membuat onde-onde karena menjadi kempes setelah dingin. Rahasianya ada di tiga hal:\n\n1. Istirahatkan adonan minimal 30 menit agar gluten terbentuk sempurna.\n2. Goreng dengan minyak banyak dan suhu sedang (160–170°C), jangan terlalu panas agar tidak pecah.\n3. Setelah matang, tiriskan di kawat kawat — bukan di atas tisu — agar uap tidak terperangkap dan membuat kempes.\n\nOnde-onde wijen kami tetap renyah sampai 8 jam karena memakai tepung ketan penuh (bukan campuran) dan wijen hitam putih premium.",
    author: "Bude Harum Dapur",
    read_time: 4,
    views: 4200,
    is_featured: false,
    published_at: "2025-09-25",
    image_url: "/images/artikel/onde-resep.svg",
  },
  {
    id: "a9",
    slug: "simbolisme-jenang-dodol-pernikahan-jawa",
    title: "Simbolisme Jenang dan Dodol dalam Tradisi Pernikahan Jawa",
    category: "Filosofi Tradisi",
    excerpt:
      "Dodol yang lengket dan lama dimasaknya adalah doa agar hubungan dua manusia juga lengket dan sabar melewati proses.",
    content:
      "Dalam tradisi Jawa, dodol dan jenang hampir selalu hadir dalam serangkaian upacara pernikahan. Bukan hanya karena rasanya manis.\n\nTekstur dodol yang lengket melambangkan harapan agar pasangan selalu lengket dan tidak mudah terpisah. Proses memasaknya yang berjam-jam sambil terus diaduk mengajarkan tentang kesabaran — persis seperti proses membangun rumah tangga.\n\nJenang, terutama jenang abang (merah) dan jenang putih, melambangkan doa yang merah berani dan murni. Kombinasinya dalam satu tampah berarti harmoni doa.\n\nDapur kami masih menyediakan dodol dan jenang handmade untuk keperluan sidang adat dan hantaran, dibuat oleh perajin tua yang telah puluhan tahun mengaduk wajan besar.",
    author: "Chef Dapur Tradisi",
    read_time: 6,
    views: 3800,
    is_featured: false,
    published_at: "2025-09-20",
    image_url: "/images/artikel/dodol.svg",
  },
  {
    id: "a10",
    slug: "hitungan-porsi-kue-tampah-arisan",
    title: "Hitungan Porsi Kue Tampah untuk Acara Arisan 30-50 Orang",
    category: "Panduan Hajatan",
    excerpt: "Jangan sampai kurang atau boros. Ini rumus porsi kue per tampah untuk berbagai skala acara.",
    content:
      "Menghitung jumlah kue untuk acara itu seni tersendiri. Berikut rumus praktis dari pengalaman ribuan acara kami:\n\n- Arisan 30 orang: 2 tampah sedang (isi 40 pcs) atau 40 snack box.\n- Arisan 50 orang: 3 tampah sedang + 1 tampah mini, atau kombinasi 50 box.\n- Rapat kantor 2 jam: 1 snack box per orang + 20% cadangan.\n- Resepsi 300 tamu: 4 tampah Tamu Agung per 100 tamu (asumsi tiap tamu mengambil 3–4 pcs).\n\nSelalu siapkan 10–15% cadangan. Lebih baik tersisa sedikit daripada tamu kehabisan kue saat acara puncak.",
    author: "Tim Katering Pawon",
    read_time: 5,
    views: 3100,
    is_featured: false,
    published_at: "2025-09-15",
    image_url: "/images/artikel/arisan.svg",
  },
  {
    id: "a11",
    slug: "kue-putu-ayu-berbusa-hijau",
    title: "Kue Putu Ayu Berbusa Hijau: Sentuhan Parutan Kelapa Setengah Tua",
    category: "Tips Dapur",
    excerpt: "Kunci putu ayu lembut berbusa ada di pemilihan kelapa dan teknik mengocok telur.",
    content:
      "Putu ayu yang sempurna harus berbusa lembut dengan gurita parutan kelapa yang menempel rapi. Dua kunci utamanya:\n\n1. Gunakan kelapa setengah tua — terlalu muda membuat parutan licin tidak menempel, terlalu tua membuat keras.\n2. Kocok telur hingga benar-benar berbusa putih pekat sebelum masukkan tepung. Ini yang menciptakan tekstur 'berbusa'.\n\nKue putu ayu dari dapur kami selalu menggunakan kelapa parut setengah tua yang diparut manual — terlihat dari serat parutan yang panjang dan menempel rapi di setiap kue.",
    author: "Bude Harum Dapur",
    read_time: 4,
    views: 2700,
    is_featured: false,
    published_at: "2025-09-10",
    image_url: "/images/artikel/putu-ayu.svg",
  },
];

export const FALLBACK_ORDERS: Order[] = [
  {
    id: "o1",
    order_code: "#PWN-8833",
    event_name: "Hantaran Syukuran & Tampah Agung",
    customer_name: "Ibu Ratih Anggraini",
    phone: "081234567890",
    location: "Kebayoran Baru",
    items: [
      { name: "Tampah Tamu Agung (80 Pcs)", qty: 1, price: 385000 },
      { name: "Kudapan Tambahan", qty: 1, price: 63500 },
    ],
    delivery_slot: "Slot Fajar Utama",
    delivery_date: "2025-10-22",
    delivery_time: "06:30",
    courier_info: "Kurir Blindvan 02",
    address: "Jl. Warisan Rasa No. 18, Kebayoran Baru, Jakarta Selatan",
    notes: "Hiasan daun pisang kepang mawar sesuai permintaan.",
    total_amount: 448500,
    payment_method: "QRIS Instan",
    payment_status: "Lunas via QRIS",
    status: "diterima",
    created_at: "2025-10-22T03:40:00",
  },
  {
    id: "o2",
    order_code: "#PWN-8821",
    event_name: "Hajatan Kantor BUMN",
    customer_name: "Bpk. Rendra",
    phone: "081234567891",
    location: "Gedung Telkom",
    items: [{ name: "Box Hajatan Mewah", qty: 60, price: 35000 }],
    delivery_slot: "Slot Fajar Utama",
    delivery_date: "2025-10-22",
    delivery_time: "06:30",
    courier_info: "Kurir Subuh (30 Menit Lagi)",
    address: "Gedung Telkom, Jakarta Pusat",
    notes: "",
    total_amount: 2100000,
    payment_method: "Transfer BCA",
    payment_status: "Lunas",
    status: "siap_kirim",
    created_at: "2025-10-21T20:10:00",
  },
  {
    id: "o3",
    order_code: "#PWN-8824",
    event_name: "Arisan Ibu Ratna",
    customer_name: "Ibu Ratna Kumalasari",
    phone: "081234567892",
    location: "Pondok Indah",
    items: [{ name: "Tampah Sultan 100 Pcs", qty: 2, price: 725000 }],
    delivery_slot: "Slot Fajar Utama",
    delivery_date: "2025-10-22",
    delivery_time: "07:30",
    courier_info: "Kurir Dapur Khusus",
    address: "Pondok Indah, Jakarta Selatan",
    notes: "Tampah bertingkat 2 tingkat.",
    total_amount: 1450000,
    payment_method: "QRIS Instan",
    payment_status: "Lunas",
    status: "sedang_ditata",
    created_at: "2025-10-21T18:45:00",
  },
  {
    id: "o4",
    order_code: "#PWN-8827",
    event_name: "Langganan Sarapan Pagi",
    customer_name: "dr. Hendra Setiawan",
    phone: "081234567893",
    location: "Menteng",
    items: [
      { name: "Klepon Gula Aren Meluber", qty: 15, price: 18000 },
      { name: "Kue Lumpur Surga Pandan", qty: 10, price: 22000 },
    ],
    delivery_slot: "Slot Fajar Utama",
    delivery_date: "2025-10-22",
    delivery_time: "06:00",
    courier_info: "Diambil Driver Ojol",
    address: "Menteng, Jakarta Pusat",
    notes: "",
    total_amount: 162500,
    payment_method: "QRIS Instan",
    payment_status: "Lunas",
    status: "siap_kirim",
    created_at: "2025-10-21T16:20:00",
  },
  {
    id: "o5",
    order_code: "#PWN-8830",
    event_name: "Syukuran Rumah Baru",
    customer_name: "Bpk. Fajar Ramadhan",
    phone: "081234567894",
    location: "Tebet",
    items: [{ name: "Snack Box Klasik", qty: 35, price: 25000 }],
    delivery_slot: "Slot Siang",
    delivery_date: "2025-10-22",
    delivery_time: "09:00",
    courier_info: "Katering Rumah",
    address: "Tebet, Jakarta Selatan",
    notes: "",
    total_amount: 875000,
    payment_method: "DP 50% Katering",
    payment_status: "DP 50%",
    status: "sedang_dikukus",
    created_at: "2025-10-21T14:05:00",
  },
  {
    id: "o6",
    order_code: "#PWN-8832",
    event_name: "Acara Pengajian Masjid",
    customer_name: "Ustadz Mansyur",
    phone: "081234567895",
    location: "Kuningan",
    items: [
      { name: "Nagasari", qty: 80, price: 4000 },
      { name: "Dadar Gulung", qty: 80, price: 4000 },
    ],
    delivery_slot: "Slot Siang",
    delivery_date: "2025-10-22",
    delivery_time: "11:30",
    courier_info: "Shift Siang",
    address: "Masjid Kuningan, Jakarta Selatan",
    notes: "",
    total_amount: 640000,
    payment_method: "Transfer Mandiri",
    payment_status: "Belum Dibayar",
    status: "menunggu_pembayaran",
    created_at: "2025-10-21T11:30:00",
  },
];
